apiVersion: v2
name: azure-storageclasses
description: A Helm chart for azure-storageclasses
version: 0.2.0-dev
appVersion: 0.2.0-dev
home: https://github.com/giantswarm/azure-storageclasses
sources:
  - https://github.com/giantswarm/azure-storageclasses
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
annotations:
  application.giantswarm.io/team: "phoenix"
  io.giantswarm.application.team: "phoenix"
